### ISSUE TITLE
ILLData doesn't sort all .lst files

### ISSUE THREAD

**Issue by K-Raymond** [UoG-Nuclear-Physics-Group/ILLData#12]
I have two 5min runs of Eu152 taken from the beginning of an experiment.

Example log output from the most up to date version of this library, and version 4.0 of GRSISort:
[Log.txt](https://github.com/UoG-Nuclear-Physics-Group/ILLData/files/3443785/Log.txt.txt)

I suspect it is with the size of the file. The Eu152 runs are 3.9GB vs the rest of the runs which are ~1.4GB. There are a set of similar runs Eu152 runs at the beginning of a previous experiment which sort fine, which are ~1.3GB.

When I take one of the 3.9GB runs and create a "subrun" of 99999997 events (using dd) to create a file which is 1.5GB, GRSISort sorts the file. I can also generate spectra fine.

I'm not sure what the issue is, or is there's something I need to implement in TLst? Any direction would be appreciated @VinzenzBildstein, or @r3dunlop?

**Comment by VinzenzBildstein** [comment]
This seems to be an issue with the TLstFile class itself, the loop that reads the input file seems to fail reading anything. This might be because we're reading the whole file into memory and then start parsing it from there.
As a first check if this could be the issue, I would try and change TLstFile::Open at line 95 or so to se fFileSize to a fixed value if in.tellg() is larger than say 1.5 GB. That would make grsisort read only part of the data. If that succeeds, you could try and check if you run out of memory when you try and sort a large file? 
Alternatively we could try and come up with a way to read only parts of the file at once. I'm also not sure we free the memory at any point after it has been parsed.

**Comment by r3dunlop** [comment]
The whole file reading was a hack on TMidasFile since it only read one event from the file at a time. Surely there is c++ chunking capability that will allow us to do this. Would just using a readline (with appropriate number of lines) in place of what we do now work?

**Comment by VinzenzBildstein** [comment]
Actually the TMidasFile handles things differently. It is back to reading events one at a time I believe (which works now that the events are larger again).
This was something implemented just for TLstFile, since I didn't know how to tell the size of a single event to read it. I don't think readline would be appropriate as that goes by newlines.
I was more thinking along the lines of using ifstream::read (as we are now), but with a maximum size for the bytes read. In TLstFile::Read we would then check the number of remaining bytes in the buffer, and if below a certain limit, we would read again up to that same maximum size (or until we hit the end of the file).

**Comment by K-Raymond** [comment]
I've made a few modifications which sorts the two larger runs. The diffs can be found [here](https://github.com/UoG-Nuclear-Physics-Group/ILLData/compare/master...K-Raymond:wip/input_files).

The gist is,
- `READ_EVENT_SIZE` defines the maximum events read from the file into the buffer at each iteration. The member function `gcount()` is used to find how many bytes were actually read from the file.
- The events are first read into a different buffer before being put into the vector `fReadBuffer`. I should optimize this with using instead a shared pointer buffer of `chars*` and write `TLstEvent` to work with shared pointers instead of vectors.

Additionally, it may be best to pass particular header information through TLstEvent such as the lst version, and rewrite the parser to unchunk TLstEvent into separate events, and process event-by-event using particular functions similar to how it is done with midas files in GRSIData. Upon consensus, I will also change the class names around/add documentation to make more sense.

**Comment by K-Raymond** [comment]
I've just noticed an issue with both the new and old libraries for the sort code. It's an issue with the current version of the code on this repo.

There is a discrepancy with the number of events passed from the event build loop to the detector build loop. For instance I have a run file with:

- According to the header, 86,395,130 events. Some of these events may be bad events ( ie, charge < 2 or the charge is roughly 2^14-1).

- 82,459,361 events end up in the good frag queue. And 82,459,361 events are placed the fragment tree after sorting.

- However, the analysis loop only sees 38,619,667 events. And the analysis tree is only populated with 38,619,667 events after sorting.

So over half of the events are not apparently not being transferred from the event build loop to the detector build loop. I don't know if this is an issue with the ILL code, or GRSISort code. I've attempted to look at the differences between ILLData and GRSIData to understand if it's a status issue, but no luck. And I don't know enough about those build loops to know where to look.

Any suggestions on where I should focus my efforts @VinzenzBildstein  or @r3dunlop?

**Comment by VinzenzBildstein** [comment]
The analysis loop only gets events that have been assembled from fragments, i.e. there can be more than one fragment per event. So it makes sense that there are less events than fragments. To check that the numbers are exactly the same, you would need to loop through all events in the analysis tree and add their multiplicities together.
